#!/bin/bash
qemu-system-x86_64 -cpu Haswell -d cpu_reset -no_reboot -smp 5 -m 4G -kernel bzImage -D /tmp/qemu.log -initrd rootfs -append "root=/dev/ram rdinit=/sbin/init memmap=0x40000000\$0x40000000 console=ttyS0,115200" -net nic -net user,hostfwd=tcp::2222-:22 -serial stdio -display none > /dev/null 2>&1 &
