#!/bin/bash
ssh -o ConnectTimeout=3 -o LogLevel=quiet -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -i /id_rsa -p ${SSH_PORT:-2222} ${SSH_USER:-hakase}@${SSH_ADDR:-localhost} $@
